### ISSUE TITLE
setIntervall - memory permanently increasing

### ISSUE THREAD

**Issue by fatelgit** [Krb686/nanotimer#14]
Hello,
I was trying to use your library for a game loop. Installation and including works like a charm but setIntervall seems to block GC. Even when I am just doing this:

``` javascript
var NanoTimer = require('nanotimer');
var timerA = new NanoTimer();
var task = function() {
    console.log(Date.now());
};
timerA.setInterval(task, null, 1000/25+'m', function(err) {
    if(err) {
        //error
    }
});
```

The memory used will increase slowly and it never drops to a lower value again. That's why I am assuming GC won't run.
Am I missing sthg.?

P.S. I am on Ubuntu 14 with node 0.12.7

**Comment by Krb686** [comment]
I'm looking into this.  I'm pretty busy at the moment, but hopefully I can find out why soon.

**Comment by mazhlekov** [comment]
@fatelgit did you try with node >=5.0, cuz there is a leak in older versions ?

**Comment by onury** [comment]
is this the case for Node 4.x
@Krb686 did you have time to check this?

**Comment by rhyek** [comment]
Hey, guys. Working on a project currently and am interested in this library for use on a microcontroller. Any news on this? Has anyone else confirmed this issue/is a fix planned?

**Comment by Krb686** [comment]
My attention has been brought back to this.  I'm running some memory leak tests now...

**Comment by fatelgit** [comment]
I've tested again with a new setup (Ubuntu 16.10, node 7.1.0) and the problem seems to be gone. Memory still increases from about 10MiB to 21MiB then jumps up to 37MiB a few minutes later but not any further. Had the example from my opening post running for about 3 hours and memory consumption never surpassed 37MiB. So I would assume that there was a leak in the older node version I've used last year.

**Comment by ericmcdaniel** [comment]
Memory leak is still occurring in node 6.x

**Comment by Krb686** [comment]
Meant to post some results from that old comment from 9/16 but I kinda dropped it after fatelgit said he no longer saw the issue.  I just kicked off a little test with 6.11, so I'll let it run overnight and see what happens.

**Comment by Krb686** [comment]
So my test was the exact code posted above by fatelgit.  Here's the vsz in KiBs  after running overnight.  Each tick on the x axis is a single second, so it has been running for almost 7.5 hours.

![mem-graph](https://user-images.githubusercontent.com/959619/27253388-aa8204e2-5341-11e7-869b-baaf94835ba2.png)

So obviously I can't really say this is confirmed yet.  Maybe you have some more interesting code you can share where you're seeing this problem? Or maybe it really isn't 6.x.  What version of node are you using?

**Comment by ericmcdaniel** [comment]
@Krb686 Awesome, thanks for sharing your results.

I'm experiencing this issue with Node v6.x on a Heroku cedar-14 stack. I'm going to do some more testing today to ensure the issue is being caused by nanotimer.

I also experienced increasing memory usage locally using Node v7.10.0. The memory leak appeared to be removed by replacing nanotimer.setTimeout with a native setTimeout call (which is not ideal because your library performs better for my use case). This proves nothing, of course. If I can create a test that definitively proves nanotimer is causing the problem, I'll share it here.

**Comment by Krb686** [comment]
@ericmcdaniel Ok, great.  Yeah that last test was in CentOS 7.1, but I also have Win10 I can try it out in.  I'll put v7.10 on it and see what happens.

**Comment by Krb686** [comment]
And here's another graph from the test above (CentOS7,1 / node 6.11) after 35 hours

![mem-graph](https://user-images.githubusercontent.com/959619/27262795-3c0c0a26-542c-11e7-9396-136be9f3d23b.png)

**Comment by Krb686** [comment]
Here is the Win10 + node 7.10 test. This is a graph of process private bytes over the course of 9 hours running the exact same code.  The graph rolled back around on the left side, but originally started at about 10pm.

![mem-graph_node7 10_8hrs](https://user-images.githubusercontent.com/959619/27283004-543d6722-54c0-11e7-8203-a17faedc57f6.png)

**Comment by ericmcdaniel** [comment]
@Krb686 I did a review of a few other potential candidates for memory leaks in my project and the memory leak I was experiencing is not due to nanotimer but a separate library :).

It seems that the increases in memory usage that I noticed when swapping in nanotimer were being deallocated correctly, and I mistakenly identified nanotimer as being the cause of the issue. Sorry about that, and thanks for sharing your test results.
