### ISSUE TITLE
timer.setInterval() takes interval as args

### ISSUE THREAD

**Issue by Tilogorn** [Krb686/nanotimer#9]
When calling the setInterval()-method like this:

    timerA.setInterval(task, '100m', function(err) {
        if(err) {
            //error 
        }
    });

where "task" is something like

    function task(){
        console.log("test");
    }

an error occurs. It says
`Interval argument to setInterval must be a string specified as an integer follow
ed by 's' for seconds, 'm' for milli, 'u' for micro, and 'n' for nanoseconds. Ex. 2u`

I observed the arguments of the setInterval-method:

    NanoTimer.prototype.setInterval = function(task, args, interval, callback){
	    console.log(task);
	    console.log(args);
	    console.log(interval);
	    console.log(callback);
        ...

The interval '100m' was always taken by `args` (which follows the logical order).
As a workaround, I deleted every use of `args`.

Tested with Node v0.10.35 and nanotimer 1.4.28 (current npm version) on Windows 8.1.

**Comment by Krb686** [comment]
Great thanks, will look at this as soon as I have time

**Comment by Krb686** [comment]
As it turns out, you are not following the argument specification for setInterval.  The 4 arguments in order are:

1) task (the function to be run)
2) args (arguments to the above function, not setInterval)
3) interval (the time interval)
4) callback (optional)

You have task specified as "task".
You have args specified as '100m'.  This means your function task will be passed '100m'.
You have function(err).... for interval
You have nothing for callback, which is fine.

So you can see how this is slightly off. What you really want is:

    timerA.setInterval(task, '', '100m', function(err){....
    ...
    }
